import type { Lead } from "@/types/lead"

export let mockLeads: Lead[] = [
  {
    id: "0",
    firstName: "Iskhak",
    lastName: "Asanov",
    email: "asanov.personal@gmail.com",
    linkedinProfile: "https://linkedin.com/in/iskhakasan",
    countryOfCitizenship: "kyrgyzstan",
    visasOfInterest: ["work"],
    resumeUrl: "/A. Iskhak - Senior Frontend Engineer.pdf",
    additionalInfo: "Experienced Frontend Developer with expertise in Javascript, Typescript, React, HTML/CSS, Redux. Proven track record of delivering high-quality and scalable web applications. Have experience of leading a small team of 3-5 people.Experienced Frontend Developer with expertise in Javascript, Typescript, React, HTML/CSS, Redux. Proven track record of delivering high-quality and scalable web applications. Have experience of leading a small team of 3-5 people.",
    status: "PENDING",
    submittedAt: "2025-02-28T16:30:00Z",
  },
  {
    id: "1",
    firstName: "Aibek",
    lastName: "Bekov",
    email: "aibek.bekov@example.com",
    linkedinProfile: "https://linkedin.com/in/aibekbek",
    countryOfCitizenship: "usa",
    visasOfInterest: ["work", "business"],
    resumeUrl: "/placeholder.svg?height=600&width=400",
    additionalInfo:
      "I'm interested in working in the tech industry and have 5 years of experience as a software engineer.",
    status: "REACHED_OUT",
    submittedAt: "2025-02-15T10:30:00Z",
  },
  {
    id: "2",
    firstName: "Aigul",
    lastName: "Guleva",
    email: "jane.smith@example.com",
    linkedinProfile: "https://linkedin.com/in/aigulguleva",
    countryOfCitizenship: "kyrgyzstan",
    visasOfInterest: ["student"],
    resumeUrl: "/placeholder.svg?height=600&width=400",
    additionalInfo: "I want to pursue a Master's degree in Computer Science.",
    status: "REACHED_OUT",
    submittedAt: "2025-02-10T14:45:00Z",
  },
  {
    id: "3",
    firstName: "Beibit",
    lastName: "Bayemirov",
    email: "michael.johnson@example.com",
    linkedinProfile: "https://linkedin.com/in/beibitbay",
    countryOfCitizenship: "kazakhstan",
    visasOfInterest: ["family", "tourist"],
    resumeUrl: "/placeholder.svg?height=600&width=400",
    status: "REACHED_OUT",
    submittedAt: "2025-02-18T09:15:00Z",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@example.com",
    linkedinProfile: "https://linkedin.com/in/emilywilliams",
    countryOfCitizenship: "usa",
    visasOfInterest: ["work"],
    resumeUrl: "/placeholder.svg?height=600&width=400",
    additionalInfo: "I'm a marketing professional with 8 years of experience looking for opportunities abroad.",
    status: "REACHED_OUT",
    submittedAt: "2025-02-20T11:00:00Z",
  }
]

